### ISSUE TITLE
ranks文件夹为空, .npy文件找不到？

### ISSUE THREAD

**Issue by GengJiahao121** [LARS-research/RelEns#2]
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 3
      1 print(f"Loading dataset: {dataset_name}")
      2 ranks = {
----> 3     'valid': [np.load(f"{rank_path}/{m}_valid_ranks.npy") for m in model_names],
      4     'test': [np.load(f"{rank_path}/{m}_test_ranks.npy") for m in model_names]
      5 }
      6 print(ranks['test'][0].shape)
      8 n_model = len(ranks['test'])

Cell In[5], line 3, in <listcomp>(.0)
      1 print(f"Loading dataset: {dataset_name}")
      2 ranks = {
----> 3     'valid': [np.load(f"{rank_path}/{m}_valid_ranks.npy") for m in model_names],
      4     'test': [np.load(f"{rank_path}/{m}_test_ranks.npy") for m in model_names]
      5 }
      6 print(ranks['test'][0].shape)
      8 n_model = len(ranks['test'])

File ~/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py:405, in load(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)
    403     own_fid = False
    404 else:
--> 405     fid = stack.enter_context(open(os_fspath(file), "rb"))
    406     own_fid = True
    408 # Code to distinguish from NumPy binary files and pickles.

FileNotFoundError: [Errno 2] No such file or directory: 'ranks/ogbl-biokg/KGBench_valid_ranks.npy'
```

**Comment by GengJiahao121** [comment]
·

**Comment by LeoYML** [comment]
Problem: The "ranks" folder is empty, and the .npy file cannot be found?
Due to the large size of the rank file, we have not uploaded it. You can place your rank file in this location. The data format of the file and how to generate it are explained in the documents and papers. If you encounter any problems, you can post your specific questions. Thanks for your attention!

**Comment by fatimaafarooq** [comment]
How I can generate rank file for OGBL datasets e.g., wikikg2 or biokg ?

**Comment by LeoYML** [comment]
Due to the large size of the rank file, we have not uploaded it. You can place your rank file in this location. The data format of the file and how to generate it are explained in the documents and papers. If you encounter any problems, you can post your specific questions. Thanks for your attention!

**Comment by fatimaafarooq** [comment]
> Due to the large size of the rank file, we have not uploaded it. You can place your rank file in this location. The data format of the file and how to generate it are explained in the documents and papers. If you encounter any problems, you can post your specific questions. Thanks for your attention!

Can you guide me which specific documents or papers? Are there multiple choices to generate rank of data

**Comment by LeoYML** [comment]
In the paper: https://aclanthology.org/2023.emnlp-main.1034/ , we explain why ranks are necessary. The script is simple and easy to code, and the paper also introduces how to generate the ranks. You can ensemble without using ranks, but based on our experiments and experience, ranks are always better, especially when your ensemble models are very different.

**Comment by LeoYML** [comment]
You can also follow the instructions in the readme.md:
Section: Prepare predictions of the base models.
